# -*- coding: utf-8 -*-
"""Duc - ETL & Logistic Regressionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfQqwTVa88WDyxgXSbYkejBjcL357lnA

#**HR Analytics: Job Change of Data Scientists**

##**Intorduction**
**Context and Content**

A company which is active in Big Data and Data Science wants to hire data scientists among people who successfully pass some courses which conduct by the company.

Many people signup for their training. Company wants to know which of these candidates are really wants to work for the company after training or looking for a new employment because **it helps to reduce the cost and time as well as the quality of training or planning the courses and categorization of candidates**.

Information related to demographics, education, experience are in hands from candidates signup and enrollment.

##**1. Extract**

###**1.1 Enrollies' data**

As enrollies are submitting their request to join the course via Google Forms, we have the Google Sheet that stores data about enrolled students, containing the following columns:

`enrollee_id`: unique ID of an enrollee

`full_name`: full name of an enrollee

`city`: the name of an enrollie's city

`gender`: gender of an enrollee

The source: https://docs.google.com/spreadsheets/d/1VCkHwBjJGRJ21asd9pxW4_0z2PWuKhbLR3gUHm-p4GI/edit?usp=sharing
"""

import pandas as pd
!pip install mysql-connector-python pandas
import mysql.connector
from sqlalchemy import create_engine

google_sheet_id = '1VCkHwBjJGRJ21asd9pxW4_0z2PWuKhbLR3gUHm-p4GI'
sheet_url = f"https://docs.google.com/spreadsheets/d/{google_sheet_id}/export?format=xlsx"
df_1 = pd.read_excel(sheet_url, sheet_name ='enrollies')
df_1.head()

"""###**1.2 Enrollies' education**

After enrollment everyone should fill the form about their education level. This form is being digitalized manually. Educational department stores it in the Excel format here: https://assets.swisscoding.edu.vn/company_course/enrollies_education.xlsx

This table contains the following columns:

- `enrollee_id`: A unique identifier for each enrollee. This integer value uniquely distinguishes each participant in the dataset.

- `enrolled_university`: Indicates the enrollee's university enrollment status. Possible values include `no_enrollment`, `Part time course`, and `Full time course`.

- `education_level`: Represents the highest level of education attained by the enrollee. Examples include `Graduate`, `Masters`, etc.

- `major_discipline`: Specifies the primary field of study for the enrollee. Examples include `STEM`, `Business Degree`, etc.
"""

df_2 = pd.read_excel('https://assets.swisscoding.edu.vn/company_course/enrollies_education.xlsx')
df_2.head()

"""###**1.3 Enrollies' working experience**

Another survey that is being collected manually by educational department is about working experience.

Educational department stores it in the CSV format here: https://assets.swisscoding.edu.vn/company_course/work_experience.csv

This table contains the following columns:

- `enrollee_id`: A unique identifier for each enrollee. This integer value uniquely distinguishes each participant in the dataset.
- `relevent_experience`: Indicates whether the enrollee has relevant work experience related to the field they are currently studying or working in. Possible values include `Has relevent experience` and `No relevent experience`.
- `experience`: Represents the number of years of work experience the enrollee has. This can be a specific number or a range (e.g., >20, <1).
- `company_size`: Specifies the size of the company where the enrollee has worked, based on the number of employees. Examples include 50−99, 100−500, etc.
- `company_type`: Indicates the type of company where the enrollee has worked. Examples include `Pvt Ltd`, `Funded Startup`, etc.
- `last_new_job`: Represents the number of years since the enrollee's last job change. Examples include never, >4, 1, etc.
"""

df_3 = pd.read_csv('https://assets.swisscoding.edu.vn/company_course/work_experience.csv')

df_3.head()

"""###**1.4 Training hours**

From LMS system's database you can retrieve a number of training hours for each student that they have completed.

**Database credentials:**

- Database type: `MySQL`
- Host: `112.213.86.31`
- Port: `3360`
- Login: `etl_practice`
- Password: `550814`
- Database name: `company_course`
- Table name: `training_hours`
"""

mydb = mysql.connector.connect(
            host="112.213.86.31",
            user="etl_practice",
            passwd="550814",
            port = '3360',
            database="company_course")

querry = "SELECT * FROM training_hours"
df_4 = pd.read_sql(querry, mydb)

"""###**1.5 City development index**

Another source that can be usefull is the table of City development index.

The City Development Index (CDI) is a measure designed to capture the level of development in cities. It may be significant for the resulting prediction of student's employment motivation.

It is stored here: https://sca-programming-school.github.io/city_development_index/index.html
"""

df_5_list = pd.read_html('https://sca-programming-school.github.io/city_development_index/index.html')
df_5 = df_5_list[0]
df_5

"""###**1.6 Employment**

From LMS database you can also retrieve the fact of employment. If student is marked as employed, it means that this student started to work in our company after finishing the course.

**Database credentials:**

- Database type: `MySQL`
- Host: `112.213.86.31`
- Port: `3360`
- Login: `etl_practice`
- Password: `550814`
- Database name: `company_course`
- Table name: `employment`
"""

querry_1 = "SELECT * FROM employment"
df_6 = pd.read_sql(querry_1, mydb)

"""##**2. Transform**

###**2.1 Enrollies' data**
"""

df_1.info()

df_1[df_1['gender'].isnull()]

df_1['gender'].value_counts(dropna = False)

df_1_notnull = df_1[~df_1['gender'].isnull()].copy()
df_1_notnull[['first_name', 'last_name']] = df_1_notnull['full_name'].str.split(expand = True)

mode_map = df_1_notnull.groupby('first_name')['gender'].apply(lambda x:x.mode().iloc[0]).to_dict()

df_1[['first_name', 'last_name']] = df_1['full_name'].str.split(expand = True)

df_1['gender'] = df_1['gender'].fillna(df_1['first_name'].map(mode_map))

df_1.info()

df_1['gender'].value_counts(dropna= False)

"""###**2.2 Enrollies' education**"""

df_2.info()

"""**Inspect unique values and the number of values in every column**"""

for col in df_2.columns.drop('enrollee_id'):
  print(df_2[col].value_counts(dropna = False))

"""**Fill missing values with 'Missing'**"""

for col in df_2.columns.drop('enrollee_id'):
  df_2[col] = df_2[col].fillna('Missing')
df_2.info()

"""**These object-type columns are categorical in nature, so they should be converted to the category data type.**"""

cat_cols = df_2.select_dtypes(include = 'object').columns
df_2[cat_cols] = df_2[cat_cols].astype('category')
df_2.info()

"""###**2.3 Enrollies' working experience**"""

df_3.info()

"""**Inspect unique values and the number of values in every column**"""

for col in df_3.columns.drop('enrollee_id'):
  print(df_3[col].value_counts(dropna = False))

"""**Fill missing values with 'Missing'**"""

for col in df_3.columns.drop('enrollee_id'):
  df_3[col] = df_3[col].fillna('Missing')
df_3.info()

"""###**2.4 Training hours**"""

df_4.info()

"""###**2.5 City development index**"""

df_5.info()

"""###**2.6 Employment**"""

df_6.info()

"""##**3. Load**

"""

db_path = '/content/data_warehouse.db'
db_engine = create_engine(f'sqlite:///{db_path}')

df_1.to_sql("Enrollies_data", db_engine, if_exists='replace', index = False)

df_2.to_sql("Enrollies_education", db_engine, if_exists='replace', index = False)

df_3.to_sql("Enrollies_working_experience", db_engine, if_exists='replace', index = False)

df_4.to_sql("Training_hours", db_engine, if_exists='replace', index = False)

df_5.to_sql("City_development_index", db_engine, if_exists='replace', index = False)

df_6.to_sql("Employment", db_engine, if_exists='replace', index = False)